# Generated by Django 2.0.2 on 2019-02-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='element',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
