# Generated by Django 2.0.2 on 2019-02-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_log_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_key',
            field=models.IntegerField(default='1'),
        ),
    ]
